pipeline:
  docker:
    image: plugins/docker
    repo: registry.tstllc.net/llisk/tstllc-alpine-scala
    username: ${REPO_USERNAME}
    password: ${REPO_PASSWORD}
    email: ${REPO_EMAILADDR}
    registry: registry.tstllc.net
#    tag:
#      - ${DRONE_BRANCH}-latest
#      - ${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}
#    force_tag: true

publish:
  docker:
    repo: registry.tstllc.net/llisk/tstllc-alpine-scala
    username: ${REPO_USERNAME}
    password: ${REPO_PASSWORD}
    email: ${REPO_EMAILADDR}
    tag:
      - latest
    when:
      branch:
        include: [ master, release/* ]

publish:
  docker:
    repo: registry.tstllc.net/llisk/tstllc-alpine-scala
    username: ${REPO_USERNAME}
    password: ${REPO_PASSWORD}
    email: ${REPO_EMAILADDR}
    tag:
      - ${DRONE_BRANCH}-latest
      - ${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}
    when:
      branch:
        exclude: [ master ]
